# Site settings
title: XR Blog
SEOTitle: 唐肖然的博客 | XR Blog
header-img: img/post-bg-desk.jpg
email: x_t9@txstate.edu
description: "Every failure is leading towards success."
keyword: "XR, XR Blog, 肖然的博客"
url: "http://xiaoran-tang.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/xiaoran-tang/xiaoran-tang.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-XR.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
github_username:    xiaoran-tang


# Build settings
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4   #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d  #同上
  repo: qiubaiying.github.io    #仓库名称
  owner: qiubaiying    #github用户名
  admin: qiubaiying
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 2              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Xiao Tian",
        href: "http://xiao-tian.github.io"
    },{
        title: "简书·BY",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
